### ISSUE TITLE
Add free text response to data viz dashboard (Affects current pilot study)

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-admin-OLD-Vue#839] opened 2021-03-04 22:19 UTC
Currently free text responses cannot be viewed on the data viz dashboard. In the current pilot, clinicians need to be able to view the free text responses of patients using the app.

Can we add tables to visualize these free text responses, showing data from 7 days at a time?

-Make sure the response column is wide and wraps text.

Date | Time | Response
-- | -- | --
MM/DD | XX:XX AM/PM | ‘fooooooo...oooooooo'
MM/DD | XX:XX AM/PM | ‘fooooooo...oooooooo'

\<\<prev - - - - - - - - - -  next\>\>

**Comment by sergeysemenuta** [comment] 2021-03-22 12:43
Works as expected on applets created via applet builder:

![2021-03-22_14-17-44.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/4876c56c-48ba-4df0-815e-90e735136250)

Text responses are not shown for applets uploaded from the git hub (dbt)
https://raw.githubusercontent.com/ChildMindInstitute/DBT_applet1/master/protocols/DBT_applet1/DBT_applet1_schema

![2021-03-22_14-42-10.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/54c75233-cbd1-4b50-9157-7bf8e963aafc)
**Environment:**
https://admin-staging.mindlogger.org/
Win 10 Chrome 89

**Comment by hotavocado** [comment] 2021-03-22 22:35
@sergeysemenuta thanks, this was a great catch. I think this speaks to a more general issue of how applets uploaded from github and those created by the builder are somehow behaving differently..

@WorldImpex @binarybottle I think we should make sure applet lifecycle looks more like this:
![good_flow](https://user-images.githubusercontent.com/24463939/112066745-49a8d780-8b3d-11eb-8c44-da9f8d571fe0.png)
and not like this: 
![bad_flow](https://user-images.githubusercontent.com/24463939/112066759-54636c80-8b3d-11eb-8075-9c5841d9fd1b.png)

**Comment by sergeysemenuta** [comment] 2021-03-29 09:35
The issue is fixed
![2021-03-29_12-33-26.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/e2f28203-bc7f-49b5-aeb9-7ff9d978d278)
https://admin-staging.mindlogger.org/
Chrome 89// Win 10
Closing this ticket out

**Closed as completed by sergeysemenuta** 2021-03-29 09:35 UTC
Labels: CMI Milestone 4, April1
