### ISSUE TITLE
🌄✨Adding a new applet messes up old applet display

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-admin-OLD-Vue#52] opened 2019-12-10 16:40 UTC
![Screen Shot 2019-12-10 at 11 34 02 AM](https://user-images.githubusercontent.com/24463939/70549064-9d0e3680-1b41-11ea-9cfb-0335f9c80060.png)
When I added a new applet, the old applet (HBN EMA, circled in red) took the default image and all text disappeared.

**Comment by shnizzedy** [comment] 2019-12-10 17:31
I think https://github.com/ChildMindInstitute/MindLogger-bug-reports/issues/70 is the root cause here. After reverting the production server to v0.6.6, and refreshing the cache on my old applet, it looks correct: 
![screenshot](https://user-images.githubusercontent.com/5974438/70553383-004f9700-1b49-11ea-9f8d-b6870c6f35b1.png)

**Comment by henryrossiter** [comment] 2019-12-19 14:21
Is anyone still experiencing this issue?

**Comment by shnizzedy** [comment] 2019-12-19 15:51
I'm curious as well. Prod is currently running [v0.7.4](https://github.com/ChildMindInstitute/mindlogger-app-backend/releases/tag/v0.7.4) and dev is running https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/253/commits/7f19e31d0e28896e116dd92b90af7bfda293c258

**Comment by henryrossiter** [comment] 2019-12-26 15:42
Closing. I believe this was caused by some schema changes. Applets with up-to-date schemas appear to be rendering correctly.

**Closed as completed by henryrossiter** 2019-12-26 15:42 UTC
Labels: bug, admin panel, schema, backend, Vue, JavaScript, Python, MongoDB, reproschema
