### ISSUE TITLE
It is possible to save the event card with empty timeout fields

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#152] opened 2020-04-21 16:06 UTC
Preconditions:
The user is logged in on the admin panel https://admin.mindlogger.org/
The user is on the event card
Steps to reproduce:
1. Check the "Allow timeout" checkbox
2. Uncheck the "All day" checkbox
3. Clear the Timeout fields and click the "Save" button
4. Pay attention to the result

Actual result: It is possible to save the event card with empty timeout fields. No validation messages are shown.

Video: https://www.dropbox.com/s/iliftw48gmgjmcm/2020-04-21_18-37-45.MP4?dl=0

Expected result: It is not possible to save the event card with empty timeout fields. The validation messages are displayed after saving the event card with empty timeout fields.

Environment:
Win 10 // Chrome 81 // Edge

**Comment by WorldImpex** [comment] 2020-04-22 20:40
duplicate of #151

**Closed as completed by WorldImpex** 2020-04-22 20:40 UTC
Labels: bug
