### ISSUE TITLE
The 'View All Contributions' link is missing on the  applet detail page

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1000] opened 2021-05-13 14:08 UTC
Steps to reproduce:
1. Open the Applet library https://library-staging.mindlogger.org/
2. Select an applet and navigate to the applet detail page
3. Observe the applet card

Actual result: The 'View All Contributions' link is missing on the  applet detail page
![2021-05-13_17-01-46.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/bd8c0b85-d80a-4a82-8c3e-ee2ca51d54fc)
Expected result: The 'View All Contributions' link is shown on the  applet detail page
Environment:
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by sergeysemenuta** [comment] 2021-05-20 12:40
The issue is fixed
![2021-05-20_15-38-33.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/1891cb34-8359-4438-80df-c1aa4f37b88f)
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by sergeysemenuta** [comment] 2021-05-21 12:59
The issue is reproduced again
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by natalia-muzyka** [comment] 2021-06-02 12:16
Is blocked by [#49]
(https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/49)
Currently, there is no ability to reach the applet detail page

**Comment by natalia-muzyka** [comment] 2021-06-04 07:50
Update 14/06

Still blocked by [#49 The blank page is displayed after clicking the "See applet detail" button](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/49)

**Comment by natalia-muzyka** [comment] 2021-06-15 12:38
Not reproduced
https://www.screencast.com/t/7MrfqJk6U

Environment:
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.101

**Comment by natalia-muzyka** [comment] 2021-06-18 07:36
@Sshetty2 Reproduces again after fixing this one:
[The "View all contributions" button is displayed for the original applet (not copied from another applet in the library)#77](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/77)

Video:
https://www.screencast.com/t/J4ykma7huwB
Environment:
https://library-staging.mindlogger.org/
Win 10 // Chrome 91
Accounts:
geria.test@gmail.com	123456
geria.test@yahoo.com	3FuuFz60

**Comment by natalia-muzyka** [comment] 2021-06-25 09:40
The issue is reproduced.

The 'View All Contributions' link is missing on the applet detail page
Video: https://www.screencast.com/t/MUjFxj6M

Environment:
https://library-staging.mindlogger.org/
Win 10 // Chrome 91

On the video the account:
geria1.test@gmail.com // 7clCm7D5 (Transfered applet, aplet password: Qwe123!!!)

**Comment by natalia-muzyka** [comment] 2021-06-29 14:17
@Sshetty2 @jj105 
Issue: The 'View All Contributions' link is missing for the transferred applet if the current owner didn't do any updates. Once the current owner adds a new activity, the link is shown up.

Expected:  [When applets are copied from the original owner in the applet store, the next owner should show this hyperlink.](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/5)

Environment:
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.114 

Account:
qatl.customer1@protonmail.com // 3FuuFz61
Applet: 123
Applet password: Qwe123!!!
Video: https://www.screencast.com/t/MPG5jF2GgNo

**Comment by natalia-muzyka** [comment] 2021-06-30 09:24
The issue is fixed
https://www.screencast.com/t/yFJcyyUDfTO

Environment:
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.114

**Closed as completed by natalia-muzyka** 2021-06-30 09:24 UTC
Labels: bug, CMI Milestone 5
